# -*- coding: utf-8 -*-
"""class3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BxHSmeMNVCAkRn7xd1RQNqxuQVvyYVAE
"""

def factorial(n): #defining function
  if n==0:
    return 1
  else:
    return n*factorial(n-1)
    number =5
    result = factorial(number)
    print("The factorial of (number) is (result)") #calling function